<?php

/**
 * @file
 */

/**
 * Implements hook_migrate_api().
 */
function mymigrate_migrate_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implements hook_menu().
 */
function mymigrate_menu() {
  $items = array();

  $items['mymigrate/source'] = array(
    'title' => 'Items for migration',
    'description' => 'Generate random items for test migrations',
    'page callback' => '_mymigrate_generate_source_items',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['mymigrate/source/%'] = array(
    'title' => 'Item for migration',
    'description' => 'Generate a single item for migration with the specified reference id',
    'page callback' => '_mymigrate_generate_source_item',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Generate a list of migration source objects.
 */
function _mymigrate_generate_source_items() {
  $limit = intval($_GET['limit']);
  $offset = intval($_GET['offset']);

  $items = array();

  for ($i = $offset; $i < $limit + $offset; $i++) {
    $items[] = _mymigrate_generate_source($i);
  }

  _mymigrate_deliver($items);
}

/**
 * Generate a single source item.
 */
function _mymigrate_generate_source_item($id) {
  $item = _mymigrate_generate_source($id);
  _mymigrate_deliver($item);
}

/**
 * Generate a source item.
 */
function _mymigrate_generate_source($id) {
  return (object) array(
    'reference' => intval($id),
    'valuea' => 'VALUE-A-' . md5(time() . rand(100, 999)),
    'valueb' => 'VALUE-B-' . md5(time() . rand(100, 999)),
  );
}

/**
 * Deliver JSON to the page.
 */
function _mymigrate_deliver($value) {
  drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
  print drupal_json_encode($value);
  ajax_footer();
}
